import Head from 'next/head'
import Header from '../components/header'
import PodcastsContainer from '../components/podcastsContainer'
import BlogSlider from '../components/blogSliderContainer'
import Gallery from '../components/gallery'
import Newsletter from '../components/newsletter'
import Footer from '../components/footer'
import { client } from '../lib/api'
import {
  GET_PODCASTS,
  GET_POSTS,
  GET_TRENDING_EPISODE,
  GET_MENU,
  GET_GALLERY,
  GET_FOOTER_OPTIONS,
  GET_HEADER_OPTIONS,
  GET_GENERAL_OPTIOS,
} from '../lib/queries'

export default function Home({
  podcasts,
  posts,
  trending,
  menu,
  gallery,
  header,
  footer,
  general,
}) {
  return (
    <div>
      <Head>
        <title>Nicasource Podcast</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Header
        trending={trending}
        menu={menu}
        header={header}
      />

      <main role="main">
        <PodcastsContainer podcasts={podcasts} />
        <BlogSlider posts={posts} />
        <Gallery gallery={gallery} />
        <Newsletter general={general} />
      </main>

      <Footer
        podcasts={podcasts}
        menu={menu}
        footer={footer}
      />
    </div>
  )
}

export async function getServerSideProps() {
  const responsePodcast = await client.query({
    query: GET_PODCASTS,
  })

  const responsePost = await client.query({
    query: GET_POSTS,
  })

  const responseTrending = await client.query({
    query: GET_TRENDING_EPISODE,
  })

  const responseMenu = await client.query({
    query: GET_MENU,
  })

  const responseGallery = await client.query({
    query: GET_GALLERY,
  })

  const responseFooter = await client.query({
    query: GET_FOOTER_OPTIONS,
  })

  const responseHeader = await client.query({
    query: GET_HEADER_OPTIONS,
  })

  const responseGeneral = await client.query({
    query: GET_GENERAL_OPTIOS,
  })

  const podcasts = responsePodcast?.data?.podcasts?.nodes
  const posts = responsePost?.data?.posts?.nodes
  const trending =
    responseTrending?.data?.themeGeneralSettings.themeSettings.trendingEpisode
  const menu = responseMenu?.data?.menus?.nodes[0]
  const gallery =
    responseGallery?.data?.themeGeneralSettings.themeSettings.gallery
  const footer = responseFooter?.data?.acfOptionsFooter.footerOptions
  const header = responseHeader?.data?.acfOptionsHeader.headerOptions
  const general = responseGeneral?.data?.themeGeneralSettings.themeSettings

  return {
    props: {
      podcasts,
      posts,
      trending,
      menu,
      gallery,
      footer,
      header,
      general,
    },
  }
}
